export const GET_ALL_ORDER_LISTEN = "ClientOrders/GET_ALL_ORDER_LISTEN"
export const GET_ALL_ORDER_SUCCESS = "ClientOrders/GET_ALL_ORDER_SUCCESS"

export const HANDLE_GET_ALL_ORDER_LOADER = "ClientOrders/HANDLE_GET_ALL_ORDER_LOADER"

export const GET_ORDER_BY_ID_LISTEN = "ClientOrders/GET_ALL_ORDER_BY_ID_LISTEN"
export const GET_ORDER_BY_ID_SUCCESS = "ClientOrders/GET_ALL_ORDER_BY_ID_SUCCESS"

export const HANDLE_GET_ORDER_BY_ID_LOADER = "ClientOrders/HANDLE_GET_ORDER_BY_ID_LOADER"

export const GET_ORDERS_BY_STATE_LISTEN = "ClientOrders/GET_ORDERS_BY_STATE_LISTEN"

export const GET_ORDERS_BY_STATE_LISTEN_PENDING = "ClientOrders/GET_ORDERS_BY_STATE_LISTEN_PENDING"
export const GET_ORDERS_BY_STATE_SUCCESS_PENDING = "ClientOrders/GET_ORDERS_BY_STATE_SUCCESS_PENDING"
export const HANDLE_PENDING_ORDER_LOADER = "ClientOrders/HANDLE_PENDING_ORDER_LOADER"

export const GET_ORDERS_BY_STATE_LISTEN_ONGOING = "ClientOrders/GET_ORDERS_BY_STATE_LISTEN_ONGOING"
export const GET_ORDERS_BY_STATE_SUCCESS_ONGOING = "ClientOrders/GET_ORDERS_BY_STATE_SUCCESS_ONGOING"
export const HANDLE_ONGOING_ORDER_LOADER = "ClientOrders/HANDLE_ONGOING_ORDER_LOADER"

export const GET_ORDERS_BY_STATE_LISTEN_COMPLETE = "ClientOrders/GET_ORDERS_BY_STATE_LISTEN_COMPLETE"
export const GET_ORDERS_BY_STATE_SUCCESS_COMPLETE = "ClientOrders/GET_ORDERS_BY_STATE_SUCCESS_COMPLETE"
export const HANDLE_COMPLETE_ORDER_LOADER = "ClientOrders/HANDLE_COMPLETE_ORDER_LOADER"

export const GET_ORDER_TIME_LINE_LISTEN = "ClientOrders/GET_ORDER_TIME_LINE_LISTEN"
export const GET_ORDER_TIME_LINE_SUCCESS = "ClientOrders/GET_ORDER_TIME_LINE_SUCCESS"

export const HANDLE_ORDER_TIME_LINE_LOADER  = "ClientOrders/HANDLE_ORDER_TIME_LINE_LOADER"

export const UPDATE_ORDER_STATE_LISTEN = "ClientOrders/UPDATE_ORDER_STATE_LISTEN"
export const UPDATE_ORDER_STATE_SUCCESS = "ClientOrders/UPDATE_ORDER_STATE_SUCCESS"

export const HANDLE_UPDATE_ORDER_STATE_LOADER = "ClientOrders/HANDLE_UPDATE_ORDER_STATE_LOADER"

export const GET_ORDER_SOURCE_FILES_LISTEN = "ClientOrders/GET_ORDER_SOURCE_FILES_LISTEN"
export const GET_ORDER_SOURCE_FILES_SUCCESS = "ClientOrders/GET_ORDER_SOURCE_FILES_SUCCESS"

export const HANDLE_GET_ORDER_SOURCE_FILES_LOADER = "ClientOrders/HANDLE_GET_ORDER_SOURCE_FILES_LOADER"

export const CREATE_ORDER_SOURCE_FILES_LISTEN = "ClientOrders/CREATE_ORDER_SOURCE_FILES_LISTEN"
export const CREATE_ORDER_SOURCE_FILES_SUCCESS = "ClientOrders/CREATE_ORDER_SOURCE_FILES_SUCCESS"

export const HANDLE_CREATE_ORDER_SOURCE_FILES_LOADER = "ClientOrders/HANDLE_CREATE_ORDER_SOURCE_FILES_LOADER"
