export const GET_ALL_ORDER_LISTEN = "ClientOrders/GET_ALL_ORDER_LISTEN"
export const GET_ALL_ORDER_SUCCESS = "ClientOrders/GET_ALL_ORDER_SUCCESS"

export const HANDLE_GET_ALL_ORDER_LOADER = "ClientOrders/HANDLE_GET_ALL_ORDER_LOADER"

export const GET_ORDER_BY_ID_LISTEN = "ClientOrders/GET_ALL_ORDER_BY_ID_LISTEN"
export const GET_ORDER_BY_ID_SUCCESS = "ClientOrders/GET_ALL_ORDER_BY_ID_SUCCESS"

export const HANDLE_GET_ORDER_BY_ID_LOADER = "ClientOrders/HANDLE_GET_ORDER_BY_ID_LOADER"

export const GET_ORDERS_BY_STATE_LISTEN = "ClientOrders/GET_ORDERS_BY_STATE_LISTEN"

export const GET_ORDERS_BY_STATE_SUCCESS_PENDING = "ClientOrders/GET_ORDERS_BY_STATE_SUCCESS_PENDING"
export const HANDLE_PENDING_ORDER_LOADER = "ClientOrders/HANDLE_PENDING_ORDER_LOADER"

export const GET_ORDERS_BY_STATE_SUCCESS_ONGOING = "ClientOrders/GET_ORDERS_BY_STATE_SUCCESS_ONGOING"
export const HANDLE_ONGOING_ORDER_LOADER = "ClientOrders/HANDLE_ONGOING_ORDER_LOADER"

export const GET_ORDERS_BY_STATE_SUCCESS_COMPLETE = "ClientOrders/GET_ORDERS_BY_STATE_SUCCESS_COMPLETE"
export const HANDLE_COMPLETE_ORDER_LOADER = "ClientOrders/HANDLE_COMPLETE_ORDER_LOADER"
