export const GET_MAIN_SERVICES_LISTEN = "MainCat/GET_MAIN_SERVICES_LISTEN"
export const GET_MAIN_SERVICE_SUCCESS = "MainCat/GET_MAIN_SERVICE_SUCCESS"

export const MAIN_CAT_LOADING_HANDLE = "MainCat/MAIN_CAT_LOADING_HANDLE"