export const GET_MAIN_SERVICES_LISTEN = "MainCat/GET_MAIN_SERVICES_LISTEN"
export const GET_MAIN_SERVICE_SUCCESS = "MainCat/GET_MAIN_SERVICE_SUCCESS"

export const MAIN_CAT_LOADING_HANDLE = "MainCat/MAIN_CAT_LOADING_HANDLE"

export const MAIN_CAT_DELETE_LISTEN = "MainCat/MAIN_CAT_DELETE_LISTEN"
export const MAIN_CAT_DELETE_SUCCESS = "MainCat/MAIN_CAT_DELETE_SUCCESS"

export const HANDLE_MAIN_CAT_DELETE_LOADER = "MainCat/HANDLE_MAIN_CAT_DELETE_LOADER"