export const GET_ALL_SUB_CAT_LISTEN = "SubCatView/GET_ALL_SUB_CAT_LISTEN"
export const GET_ALL_SUB_CAT_SUCCESS = "SubCatView/GET_ALL_SUB_CAT_SUCCESS"

export const HANDLE_SUB_CAT_LOADING = "SubCatView/HANDLE_SUB_CAT_LOADING"

export const GET_SUB_CAT_BY_ID_LISTEN = "SubCatView/GET_SUB_CAT_BY_ID_LISTEN"
export const GET_SUB_CAT_BY_ID_SUCCESS = "SubCatView/GET_SUB_CAT_BY_ID_SUCCESS"

export const HANDLE_SUB_CAT_BY_ID_LOADING = "SubCatView/HANDLE_SUB_CAT_BY_ID_LOADING"

export const CREATE_SUB_CAT_LISTEN = "SubCatView/CREATE_SUB_CAT_LISTEN"
export const CREATE_SUB_CAT_SUCCESS = "SubCatView/CREATE_SUB_CAT_SUCCESS"

export const HANDLE_SUB_CAT_CREATE_LOADING = "SubCatView/HANDLE_SUB_CAT_CREATE_LOADING"

export const SIGNOUT_LISTEN = "SubCatView/SIGNOUT_LISTEN"

export const UPDATE_SUB_SERVICE_BY_ID_LISTEN = "SubCatView/UPDATE_SUB_SERVICE_BY_ID_LISTEN"
export const UPDATE_SUB_SERVICE_BY_ID_SUCCESS = "SubCatView/UPDATE_SUB_SERVICE_BY_ID_SUCCESS"

export const HANDLE_UPDATE_SUB_SERVICE_LOADER = "SubCatView/HANDLE_UPDATE_SUB_SERVICE_LOADER"

export const DELETE_SUB_CAT_LISTEN = "SubCatView/DELETE_SUB_CAT_LISTEN"
export const DELETE_SUB_CAT_SUCCESS = "SubCatView/DELETE_SUB_CAT_SUCCESS"

export const HANDLE_SUB_CAT_LOADER = "SubCatView/HANDLE_SUB_CAT_LOADER"