export const GET_ALL_SUB_CAT_LISTEN = "SubCatView/GET_ALL_SUB_CAT_LISTEN"
export const GET_ALL_SUB_CAT_SUCCESS = "SubCatView/GET_ALL_SUB_CAT_SUCCESS"

export const HANDLE_SUB_CAT_LOADING = "SubCatView/HANDLE_SUB_CAT_LOADING"

export const GET_SUB_CAT_BY_ID_LISTEN = "SubCatView/GET_SUB_CAT_BY_ID_LISTEN"
export const GET_SUB_CAT_BY_ID_SUCCESS = "SubCatView/GET_SUB_CAT_BY_ID_SUCCESS"

export const HANDLE_SUB_CAT_BY_ID_LOADING = "SubCatView/HANDLE_SUB_CAT_BY_ID_LOADING"
