export const GET_ALL_SUB_CAT_LISTEN = "SubCatView/GET_ALL_SUB_CAT_LISTEN"
export const GET_ALL_SUB_CAT_SUCCESS = "SubCatView/GET_ALL_SUB_CAT_SUCCESS"

export const HANDLE_SUB_CAT_LOADING = "SubCatView/HANDLE_SUB_CAT_LOADING"