export const CREATE_REQUIRED_PAGE_LISTEN = "RequiredPage/CREATE_REQUIRED_PAGE_LISTEN"
export const CREATE_REQUIRED_PAGE_SUCCESS = "RequiredPage/CREATE_REQUIRED_PAGE_SUCCESS"

export const HANDLE_CREATE_REQUIRED_PAGE_LOADER = "RequiredPage/HANDLE_CREATE_REQUIRED_PAGE_LOADER"

export const GET_REQUIRED_PAGE_LISTEN = "RequiredPage/GET_REQUIRED_PAGE_LISTEN"
export const GET_REQUIRED_PAGE_SUCCESS = "RequiredPage/GET_REQUIRED_PAGE_SUCCESS"

export const HANDLE_GET_REQUIRED_PAGE_LOADER = "RequiredPage/HANDLE_GET_REQUIRED_PAGE_LOADER"

export const DELETE_REQUIRED_PAGE_LISTEN = "RequiredPage/DELETE_REQUIRED_PAGE_LISTEN"
export const DELETE_REQUIRED_PAGE_SUCCESS = "RequiredPage/DELETE_REQUIRED_PAGE_SUCCESS"

export const HANDLE_DELETE_REQUIRED_PAGE_LOADER = "RequiredPage/HANDLE_DELETE_REQUIRED_PAGE_LOADER"

export const UPDATE_REQUIRED_PAGE_LISTEN = "RequiredPage/UPDATE_REQUIRED_PAGE_LISTEN"
export const UPDATE_REQUIRED_PAGE_SUCCESS = "RequiredPage/UPDATE_REQUIRED_PAGE_SUCCESS"

export const HANDLE_UPDATE_REQUIRED_PAGE_LOADER = "RequiredPage/HANDLE_UPDATE_REQUIRED_PAGE_LOADER"

