export const CREATE_MAIN_SERVICE_LISTEN = "MainCatCreate/CREATE_MAIN_SERVICE_LISTEN"
export const CREATE_MAIN_SERVICE_SUCCESS = "MainCatCreate/CREATE_MAIN_SERVICE_SUCCESS"

export const HANDLE_MAIN_CREATE_LOADING = "MainCatCreate/HANDLE_MAIN_CREATE_LOADING"